---
- name: Add Nodesource Keys
  apt_key:
    url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state=present
- name: add nodejs repo
  apt_repository:
    repo: deb https://deb.nodesource.com/node_7.x jessie main
    filename: 'nodesource'
    state: present
- name: add nodejs src-repo
  apt_repository:
    repo: deb-src https://deb.nodesource.com/node_7.x jessie main
    filename: 'nodesource'
    state: present
- name: Update apt cache
  apt:
    update_cache: yes
- name: Install nodejs android-tools-adb usbmount
  apt: name={{item}} state=latest
  with_items:
       - nodejs
       - android-tools-adb
       - usbmount
- name: copy kiosk.service
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
#    - { src: 'files/bridge.conf', dest: '/etc/init/bridge.conf' }
    - { src: 'files/80-removable-storage.rules', dest: '/etc/udev/rules.d/80-removable-storage.rules' }
    - { src: 'files/kiosk.service', dest: '/lib/systemd/system/kiosk.service' }
#    - { src: 'files/bridge.service', dest: '/lib/systemd/system/bridge.service' }
- git:
    repo: https://bchodbot:Pf4EZGEu@github.com/BaseChord/KioskDistribution.git
    dest: /var/www/kiosk
- name: create /var/www/kiosk/public/app
    file:
        path: /var/www/kiosk/public/app
        state: directory
        mode: 0755    
#- name: copy bridge files
#  copy: 
#    src: files/bridge/ 
#    dest: /var/www/bridge/
#    mode: 0755
- name: copy kiosk files
  copy: 
    src: files/kiosk/ 
    dest:  /opt/kiosk/
    owner: acadmin
    group: acadmin
    mode: 0755
#- service:
#    name: bridge.service
#    enabled: yes
#    state: started
- service:
    name: kiosk.service
    enabled: yes
    state: started