---
#- name: Create bridge directory
#  file:
#    path: /var/www/bridge
#    state: directory
#    mode: 0755
- name: copy adb
  copy: 
    src: files/adb 
    dest:  /usr/bin/adb
    mode: 0755
- name: bridge files
  copy: 
    src: files/bridge/ 
    dest: /var/www/bridge/
#    owner: root
#    group: root
    mode: 0755
