---
- name: Add group kiosk
  group: 
    name: kiosk
- name: Add group acadmin
  group: 
    name: acadmin
- name: Add user kiosk
  user: 
    name: kiosk
    group: kiosk
    password: $6$rounds=656000$HVXxKXYOOZ7lAsgW$NBu3.rOIjv.89lhWrctaVF/0ut6RbXX5Syy/5IO2G6vw.yHx26iJsazJSIozYJDEJikwX5LVqvegZrqH1VGzK0
- name: Add user acadmin
  user: 
    name: acadmin
    groups: sudo,acadmin
    password: $6$rounds=656000$HVXxKXYOOZ7lAsgW$NBu3.rOIjv.89lhWrctaVF/0ut6RbXX5Syy/5IO2G6vw.yHx26iJsazJSIozYJDEJikwX5LVqvegZrqH1VGzK0   
- name: Install basic software 
  apt: name={{item}} state=installed
  with_items:
       - chromium-browser
       - xorg
       - matchbox 
       - nodm
- name: Copy nodm config
  copy: 
    src: files/nodm 
    dest: /etc/default/nodm
    owner: root
    group: root
    mode: 0644
- name: Create file .xsession
  copy: 
    src: files/_.xsession 
    dest: /home/kiosk/.xsession 
    owner: kiosk
    group: kiosk
    mode: 0644