---
- name: install autossh
  apt: 
    name: autossh 
    state: latest
- name: copy sshtunnel files
  copy: 
    src: "{{ item }}" 
    dest: /opt/sshtunnel/
    owner: root
    group: root
    mode: 0755
    with_fileglob:
        - files/*
- name: Execute ensuretunnel.sh
    shell: /opt/sshtunnel/ensuretunnel.sh 4
- name: check service running
  service: name=mongodb state=started